/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bat = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({ 'bat' : Bat, 'quantity' : IDL.Nat });
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'total' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  'addBat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'checkout' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getBats' : IDL.Func([], [IDL.Vec(Bat)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bat = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'bat' : Bat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'total' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    'addBat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'checkout' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getBats' : IDL.Func([], [IDL.Vec(Bat)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };